#!/bin/sh

test_files=("bitwise_output" "bitwise_recursion" "integration" "pedersen_test" "struct" )

cargo build --release

for file in ${test_files[@]}; do
    cairo-compile "support/$file.cairo" --output "support/traces/$file.json"

    cairo_output=$( (cairo-run --layout all --print_output --program "support/traces/$file.json" --trace_file "support/traces/$file.trace") | tr -dc 0-9 ) 
    cleopatra_output=$( (../target/release/cleopatra-run --print_output "support/traces/$file.json" --trace "support/traces/$file.cleo.trace") | tr -dc 0-9 )

    if [[ $cairo_output != $cleopatra_output ]]; then
        echo "Warning: Cairo output ($cairo_output) and Cleopatra output ($cleopatra_output) differ"
    fi

    if ! diff -q support/traces/$file{,.cleo}.trace; then
        echo "Traces for $file differ"
        exit 1
    else
        echo "Traces for $file match"
    fi
done

rm support/traces/*
